### ISSUE TITLE
Download error / unable to install with pip install URL

### ISSUE THREAD

**Issue by Mhaalk** [smorad/arm64-popular-wheels#2]
hello,

thanks for sharing these wheels.
I run with ubuntu 20.04 on a RaspPi 4B 8Go, but I receive an error when I try to install them via pip:

```
~$ pip install https://github.com/smorad/arm64-popular-wheels/blob/master/aarch64/ubuntu_20.04/ray-1.2.0.dev0-cp38-cp38-linux_aarch64.whl
Collecting ray==1.2.0.dev0
  Downloading https://github.com/smorad/arm64-popular-wheels/blob/master/aarch64/ubuntu_20.04/ray-1.2.0.dev0-cp38-cp38-linux_aarch64.whl
     - 112 kB 2.2 MB/s
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    local_path = unpack_url(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 282, in unpack_url
    return unpack_http_url(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 164, in unpack_http_url
    unpack_file(from_path, location, content_type)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/unpacking.py", line 249, in unpack_file
    unzip_file(
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

any idea on how to make it work?

**Comment by Mhaalk** [comment]
Ok, first problem solved, for a reason I can't understand neither pip nor curl managed to properly download the wheel from the URL.
But when downloaded it through GitHub GUI on my laptop and scp it to my server instead, pip can install it with the .whl copied locally

---
Edit1: 
apparently the "download" button on the GUI call .../arm64-popular-wheels/**raw**/master/...
while the webpage URL is ...arm64-popular-wheels/**blob**/master/... I'll retry pip with the correct one to see if it work

---
Edit2: 

```
pip install https://github.com/smorad/arm64-popular-wheels/raw/master/aarch64/ubuntu_20.04/ray-2.0.0.dev0-cp38-cp38-linux_aarch64.whl 
```
-> work properly :)
